// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package httpclient

import (
	"golang.org/x/oauth2"
	"net/http"
)

// Injectors from wire.go:

func NewClient(tokenSource oauth2.TokenSource) *http.Client {
	roundTripper := newTransport(tokenSource)
	client := newClient(roundTripper)
	return client
}
